### ISSUE TITLE
Clean up naming scheme

### ISSUE THREAD

**Issue by ehsteve** [sunpy/tutorial-notebooks#4]
Great suggestion from @mbobra.

Notebooks could be better named with a convention such as 
`YYYY-MM-DD_MeetingName_MeetingLocation_NotebookTopic.ipynb`
and for the folders 
`YYYY_MeetingName_MeetingLocation`. 

Also should move 2016SPD-Python-SunPy into 2016_spd and the same for 2017, so there is one consistent place to look for tutorial notebooks.

**Comment by mbobra** [comment]
@ehsteve submitted a pr
